---
abstract: 'Load/save PDL from/to CSV file (optimized for speed and large data)'
author:
  - 'KMX <kmx@cpan.org>'
build_requires:
  Exporter: 5.59
  PDL: 0
  Scalar::Util: 0
  Test::More: 0.88
  Test::Number::Delta: 1.05
  Text::CSV_XS: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-IO-CSV
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 5.59
  PDL: 0
  Scalar::Util: 0
  Text::CSV_XS: 0
resources:
  repository: https://github.com/kmx/pdl-io-csv
version: 0.005
